#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-javassist
Version  : el.3.18.1
Release  : 4
URL      : https://github.com/jboss-javassist/javassist/archive/rel_3_18_1_ga.tar.gz
Source0  : https://github.com/jboss-javassist/javassist/archive/rel_3_18_1_ga.tar.gz
Source1  : https://repo1.maven.org/maven2/org/javassist/javassist/3.18.1-GA/javassist-3.18.1-GA.jar
Source2  : https://repo1.maven.org/maven2/org/javassist/javassist/3.18.1-GA/javassist-3.18.1-GA.pom
Source3  : https://repo1.maven.org/maven2/org/javassist/javassist/3.19.0-GA/javassist-3.19.0-GA.jar
Source4  : https://repo1.maven.org/maven2/org/javassist/javassist/3.19.0-GA/javassist-3.19.0-GA.pom
Source5  : https://repo1.maven.org/maven2/org/javassist/javassist/3.20.0-GA/javassist-3.20.0-GA.jar
Source6  : https://repo1.maven.org/maven2/org/javassist/javassist/3.20.0-GA/javassist-3.20.0-GA.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : MPL-1.1
Requires: mvn-javassist-data = %{version}-%{release}
Requires: mvn-javassist-license = %{version}-%{release}
BuildRequires : apache-ant
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
<html>
<HEAD>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>Read Me First</TITLE>
</HEAD>
<body>

%package data
Summary: data components for the mvn-javassist package.
Group: Data

%description data
data components for the mvn-javassist package.


%package license
Summary: license components for the mvn-javassist package.
Group: Default

%description license
license components for the mvn-javassist package.


%prep
%setup -q -n javassist-rel_3_18_1_ga

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-javassist
cp License.html %{buildroot}/usr/share/package-licenses/mvn-javassist/License.html
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/javassist/javassist/3.18.1-GA
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/javassist/javassist/3.18.1-GA/javassist-3.18.1-GA.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/javassist/javassist/3.18.1-GA
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/javassist/javassist/3.18.1-GA/javassist-3.18.1-GA.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/javassist/javassist/3.19.0-GA
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/javassist/javassist/3.19.0-GA/javassist-3.19.0-GA.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/javassist/javassist/3.19.0-GA
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/javassist/javassist/3.19.0-GA/javassist-3.19.0-GA.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/javassist/javassist/3.20.0-GA
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/javassist/javassist/3.20.0-GA/javassist-3.20.0-GA.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/javassist/javassist/3.20.0-GA
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/javassist/javassist/3.20.0-GA/javassist-3.20.0-GA.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/javassist/javassist/3.18.1-GA/javassist-3.18.1-GA.jar
/usr/share/java/.m2/repository/org/javassist/javassist/3.18.1-GA/javassist-3.18.1-GA.pom
/usr/share/java/.m2/repository/org/javassist/javassist/3.19.0-GA/javassist-3.19.0-GA.jar
/usr/share/java/.m2/repository/org/javassist/javassist/3.19.0-GA/javassist-3.19.0-GA.pom
/usr/share/java/.m2/repository/org/javassist/javassist/3.20.0-GA/javassist-3.20.0-GA.jar
/usr/share/java/.m2/repository/org/javassist/javassist/3.20.0-GA/javassist-3.20.0-GA.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-javassist/License.html
